@preconcurrency import AppKit
@preconcurrency import ApplicationServices
@preconcurrency import CoreGraphics

/// Identifies only events generated by this app so its direction filter does
/// not transform them a second time. This marker is not a security identity.
enum ScrollFixSyntheticEvent {
    static let autoScrollMarker: Int64 = 0x53_43_52_4F_4C_4C_46_58
    static let wheelSmoothMarker: Int64 = 0x53_46_57_48_45_45_4C_31

    static func isGenerated(_ event: CGEvent) -> Bool {
        let marker = event.getIntegerValueField(.eventSourceUserData)
        return marker == autoScrollMarker || marker == wheelSmoothMarker
    }
}

/// In-memory QA metrics: timing, scroll deltas and the latest middle-target
/// category. No cursor coordinates, target applications, button history or text.
struct AutoScrollDiagnostics {
    var lastMiddleClickTarget: MiddleClickTarget?
    var lastMiddleClickMilliseconds: Double?
    var maxMiddleClickMilliseconds: Double?

    mutating func recordMiddleClick(target: MiddleClickTarget, milliseconds: Double) {
        guard milliseconds.isFinite, milliseconds >= 0 else { return }
        lastMiddleClickTarget = target
        lastMiddleClickMilliseconds = milliseconds
        maxMiddleClickMilliseconds = max(maxMiddleClickMilliseconds ?? 0, milliseconds)
    }

    mutating func resetScrollMetrics() {
        lastTickMilliseconds = nil
        maxTickMilliseconds = nil
        delayedTicks = 0
        postedEvents = 0
        lastPostedDelta = nil
    }

    var lastTickMilliseconds: Double?
    var maxTickMilliseconds: Double?
    var delayedTicks: UInt64 = 0
    var postedEvents: UInt64 = 0
    var lastPostedDelta: AutoScrollPhysics.Delta?

    mutating func recordTick(milliseconds: Double) {
        guard milliseconds.isFinite, milliseconds >= 0 else { return }
        lastTickMilliseconds = milliseconds
        maxTickMilliseconds = max(maxTickMilliseconds ?? 0, milliseconds)
        if milliseconds > 24 { delayedTicks &+= 1 }
    }

    mutating func recordPosted(_ delta: AutoScrollPhysics.Delta) {
        postedEvents &+= 1
        lastPostedDelta = delta
    }
}

/// Optional Windows-style autoscroll. It owns a separate mouse-button tap, so
/// the regular scroll-direction filter keeps working if autoscroll is off.
@MainActor
final class AutoScrollController {
    private var worker: MiddleClickTapWorker?
    private var timer: DispatchSourceTimer?
    private let indicator = AutoScrollIndicator()
    private var physics = AutoScrollPhysics()
    private var scrollEventSource: CGEventSource?
    private var anchor: CGPoint?
    private var wantsScrolling = false
    private var desiredEnabled = false
    private var generation: UInt64 = 0
    private var lastSequence: UInt64 = 0
    private var lastTickAt: UInt64?
    private let collectDiagnostics: Bool
    private(set) var diagnostics = AutoScrollDiagnostics()
    private(set) var isRunning = false
    private(set) var isPausedByUserInput = false
    var isScrolling: Bool { anchor != nil }
    var onInteraction: (@MainActor () -> Void)?

    init(collectDiagnostics: Bool = false) {
        self.collectDiagnostics = collectDiagnostics
    }

    deinit { worker?.shutdown() }

    private func prepareWorker() {
        guard worker == nil else { return }
        worker = MiddleClickTapWorker(collectDiagnostics: collectDiagnostics) { [weak self] snapshot in
            DispatchQueue.main.async { [weak self] in self?.receive(snapshot) }
        }
    }

    private func receive(_ snapshot: MiddleClickTapWorker.Snapshot) {
        guard snapshot.generation == generation, snapshot.sequence > lastSequence else { return }
        lastSequence = snapshot.sequence
        isRunning = snapshot.running
        isPausedByUserInput = snapshot.paused
        if snapshot.interaction { onInteraction?() }
        if let target = snapshot.target, let milliseconds = snapshot.lookupMilliseconds {
            diagnostics.recordMiddleClick(target: target, milliseconds: milliseconds)
        }
        switch snapshot.action {
        case .unchanged: break
        case .stop: stopScrolling()
        case .start(let point):
            guard desiredEnabled, snapshot.running else { stopScrolling(); return }
            wantsScrolling = true
            startScrolling(at: point)
        }
    }

    func start() {
        if !desiredEnabled {
            desiredEnabled = true
            generation &+= 1
        }
        if scrollEventSource == nil {
            scrollEventSource = CGEventSource(stateID: .combinedSessionState)
            scrollEventSource?.localEventsSuppressionInterval = 0
        }
        guard scrollEventSource != nil else { return }
        prepareWorker()
        worker?.configure(enabled: true, generation: generation)
    }

    func stop() {
        if desiredEnabled {
            desiredEnabled = false
            generation &+= 1
        }
        stopScrolling()
        isRunning = false
        worker?.configure(enabled: false, generation: generation)
    }

    func rebuild(enabled: Bool) {
        generation &+= 1
        desiredEnabled = enabled
        stopScrolling()
        isRunning = false
        if enabled {
            if scrollEventSource == nil {
                scrollEventSource = CGEventSource(stateID: .combinedSessionState)
                scrollEventSource?.localEventsSuppressionInterval = 0
            }
            guard scrollEventSource != nil else { return }
            prepareWorker()
        }
        worker?.configure(enabled: enabled, generation: generation, rebuild: true)
    }

    func resumeAfterUserInputDisable() {
        worker?.resume()
    }

    private func startScrolling(at point: CGPoint) {
        guard isRunning else { stopScrolling(); return }
        timer?.cancel()
        anchor = point
        physics.reset()
        if collectDiagnostics { diagnostics.resetScrollMetrics() }
        indicator.show(at: point)
        lastTickAt = DispatchTime.now().uptimeNanoseconds
        let source = DispatchSource.makeTimerSource(queue: .main)
        source.schedule(deadline: .now() + .milliseconds(AutoScrollPhysics.tickIntervalMilliseconds),
                        repeating: .milliseconds(AutoScrollPhysics.tickIntervalMilliseconds),
                        leeway: .milliseconds(1))
        source.setEventHandler { [weak self] in self?.emitTick() }
        timer = source
        source.resume()
    }

    private func stopScrolling() {
        wantsScrolling = false
        timer?.cancel()
        timer = nil
        anchor = nil
        lastTickAt = nil
        physics.reset()
        indicator.hide()
    }

    private func emitTick() {
        guard wantsScrolling, isRunning, let anchor, let scrollEventSource else {
            stopScrolling()
            return
        }
        let pointer = NSEvent.mouseLocation
        let height = CGDisplayBounds(CGMainDisplayID()).height
        guard height.isFinite, height > 0, pointer.x.isFinite, pointer.y.isFinite else {
            stopScrolling()
            return
        }
        let now = DispatchTime.now().uptimeNanoseconds
        let elapsed = lastTickAt.map { Double(now &- $0) / 1_000_000_000 } ?? 0.016
        lastTickAt = now
        if collectDiagnostics { diagnostics.recordTick(milliseconds: elapsed * 1_000) }
        let offset = CGVector(dx: pointer.x - anchor.x, dy: pointer.y - anchor.y)
        guard let delta = physics.tick(offset: offset, elapsedSeconds: elapsed),
              let event = CGEvent(scrollWheelEvent2Source: scrollEventSource, units: .pixel,
                                  wheelCount: 2, wheel1: delta.vertical,
                                  wheel2: delta.horizontal, wheel3: 0) else { return }
        event.timestamp = now
        event.location = CGPoint(x: pointer.x, y: height - pointer.y)
        event.setIntegerValueField(.eventSourceUserData, value: ScrollFixSyntheticEvent.autoScrollMarker)
        event.post(tap: .cgSessionEventTap)
        if collectDiagnostics { diagnostics.recordPosted(delta) }
    }
}
